=== legend8891/sextortion-investigation-toolkit/src/utility/schemas/insta-chatlog-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "participants": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "messages": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "sender_name": {
            "type": "string"
          },
          "timestamp_ms": {
            "type": "number"
          },
          "content": {
            "type": "string"
          },
          "is_geoblocked_for_viewer": {
            "type": "boolean"
          }
        },
        "required": [
          "sender_name",
          "timestamp_ms",
          "content",
          "is_geoblocked_for_viewer"
        ]
      }
    },
    "title": {
      "type": "string"
    },
    "is_still_participant": {
      "type": "boolean"
    },
    "thread_path": {
      "type": "string"
    },
    "magic_words": {
      "type": "array",
      "items": {}
    }
  },
  "required": [
    "participants",
    "messages",
    "title",
    "is_still_participant",
    "thread_path",
    "magic_words"
  ]
}

=== legend8891/sextortion-investigation-toolkit/test/chat_logs/insta-example-chatlog.json
{
  "participants": [
    {
      "name": "alice"
    },
    {
      "name": "bob"
    }
  ],
  "messages": [
    {
      "sender_name": "bob",
      "timestamp_ms": 1713100879253,
      "content": "bye",
      "is_geoblocked_for_viewer": false
    },
    {
      "sender_name": "alice",
      "timestamp_ms": 1713100876853,
      "content": "Ok, see you later",
      "is_geoblocked_for_viewer": false
    },
    {
      "sender_name": "bob",
      "timestamp_ms": 1713100868625,
      "content": "I got to go, i'll speak to you later",
      "is_geoblocked_for_viewer": false
    },
    {
      "sender_name": "alice",
      "timestamp_ms": 1713100838398,
      "content": "Cool cool, nothing really just chilling",
      "is_geoblocked_for_viewer": false
    },
    {
      "sender_name": "bob",
      "timestamp_ms": 1713100808043,
      "content": "Not much really just at work, u?",
      "is_geoblocked_for_viewer": false
    },
    {
      "sender_name": "alice",
      "timestamp_ms": 1713100794415,
      "content": "What are you up to?",
      "is_geoblocked_for_viewer": false
    },
    {
      "sender_name": "alice",
      "timestamp_ms": 1713100754349,
      "content": "\u00f0\u009f\u0098\u0081",
      "is_geoblocked_for_viewer": false
    },
    {
      "sender_name": "alice",
      "timestamp_ms": 1713100743610,
      "content": "Yh good thanks",
      "is_geoblocked_for_viewer": false
    },
    {
      "sender_name": "bob",
      "timestamp_ms": 1713100736606,
      "content": "Hello, i'm good thank you. Wbu?",
      "is_geoblocked_for_viewer": false
    },
    {
      "sender_name": "alice",
      "timestamp_ms": 1713100712613,
      "content": "Hi there how are you?",
      "is_geoblocked_for_viewer": false
    }
  ],
  "title": "alice",
  "is_still_participant": true,
  "thread_path": "inbox/alice_545084586892063",
  "magic_words": []
}
